[tool.poetry]
name = "langgraph"
version = "0.1.0"
description = "Langgraph Agent for adaptive Document Chat"
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.black]
line_length=88

[tool.isort]
profile="black"
src_paths=["src","tests"]
